// token generation
const jwt = require("jsonwebtoken");
payload = {
  usename: "Joyce",
  role: "engineer",
};
options = {
  algorithm: "HS256",
  expiresIn: "7d",
  audience: "myDeveloperPortal",
  issuer: "nodeJSLibrary",
  subject: "loginUser",
};

const secretKey = "B7F12B3D-0BFA-4CDE-B27C-2F2573ECC2D9"; // GUID
jwt.sign(payload, secretKey, options, (error, token) => {
  console.log("logging token generated by the node library", token);
});

// token validation, check if signature is correct
const token =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VuYW1lIjoiSm95Y2UiLCJyb2xlIjoiZW5naW5lZXIiLCJpYXQiOjE1OTU4NDM4OTksImV4cCI6MTU5NjQ0ODY5OSwiYXVkIjoibXlEZXZlbG9wZXJQb3J0YWwiLCJpc3MiOiJub2RlSlNMaWJyYXJ5Iiwic3ViIjoibG9naW5Vc2VyIn0.eZlI3T5AwepsejFN0SK_tdBHTv-3laMNP3d6-uH7yU0";
jwt.verify(token, secretKey, { algorithms: "HS256" }, (error, decodedToken) => {
  if (!error) {
    console.log("logging decoded payload ", decodedToken);
  } else {
    console.log("logging decoding error", error);
  }
});
