version: "3.8"
services:
  # webapp:
  #   build: .
  #   command: npm run start
  #   ports:
  #     - "8000:8000"

  # mongo:
  #   image: mongo
  #   restart: always
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: examlsple
  webapp:
    build: "93bb0dd0a67c"
    command: npm run start
    ports:
      - "8000:8000"
      networks:
        - network
      depends_on:
        - db

    
      db:
        build: "ba0c2ff8d362"
        ports:
          - "27017:27017"  
        environment:
          MONGO_INITDB_ROOT_USERNAME: "jz"
          MONGO_INITDB_ROOT_PASSWORD: "secret"
        
        # volumes:
        #   - #load default config for mondodb from here
        #   - "db-data-store:/data/db" # path depends on which image you use
        networks:
          - network



    
        # volumes:
        #   - #mount project code on container
       

networks:
  network:
    driver: bridge