swagger: "2.0"
x-swagstar:
  category: "Regulations & Compliance:Regulatory Reporting"
x-generation-date: "March 19, 2020 8:58 AM"
x-workspaceId: qhAvZakoARiuseau8
externalDocs:
  description: API Docs
  url: "https://developer.nab.com.au"
info:
  title: Discovery
  description: Retrieve scheduled outages and health check status for Open Banking APIs.
  version: v1.0
  contact:
    name: "Nab OB API Team"
    url: "https://developer.nab.com.au"
    email: "nabapi@nab.com.au"
host: openbank.api.nab.com.au
basePath: "/cds-au/v1"
schemes:
  - "https"
tags:
  - name: Discovery
    description: "Retrieve scheduled outages and health check status for Open Banking APIs."
produces:
  - application/json
paths:
  servers:
    - url: https://openbank.api.nab.com.au
      description: Live Server
  /discovery/outages:
    x-swagstar:
      name: GET-Outages
    get:
      x-swagstar:
        apiAuth: jwt
        apiTarget:
          - service
          - openbank
        plugins:
          route-rate-limiting:
            second: 10
      tags:
        - "Common"
        - "Discovery"
      summary: "Get Outages"
      description: "Obtain a list of scheduled outages for the implementation"
      operationId: "getOutages"
      parameters:
        - $ref: "#/parameters/RequestHeader_x-v"
        - $ref: "#/parameters/RequestHeader_x-min-v"
      responses:
        200:
          description: "Request completed successfully."
          schema:
            $ref: "#/definitions/ResponseDiscoveryOutagesList"
          headers:
            x-v:
              type: "string"
              description: "The [version](##response-headers) of the API end point\
                \ that the holder has responded with."
      x-version: "1"
  /discovery/status:
    x-swagstar:
      name: GET-Status
    get:
      x-swagstar:
        apiAuth: jwt
        apiTarget:
          - service
          - openbank
        plugins:
          route-rate-limiting:
            second: 10
      tags:
        - "Common"
        - "Discovery"
      summary: "Get Status"
      description: "Obtain a health check status for the implementation"
      operationId: "getStatus"
      parameters:
        - $ref: "#/parameters/RequestHeader_x-v"
        - $ref: "#/parameters/RequestHeader_x-min-v"
      responses:
        200:
          description: "Request completed successfully."
          schema:
            $ref: "#/definitions/ResponseDiscoveryStatus"
          headers:
            x-v:
              type: "string"
              description: "The [version](##response-headers) of the API end point\
                \ that the holder has responded with."
      x-version: "1"
definitions:
  ResponseDiscoveryOutagesList:
    type: "object"
    required:
      - "links"
      - "data"
    properties:
      data:
        $ref: "#/definitions/ResponseDiscoveryOutagesList_data"
      links:
        $ref: "#/definitions/Links"
      meta:
        $ref: "#/definitions/Meta"
  ResponseDiscoveryOutagesList_data:
    required:
      - "outages"
    properties:
      outages:
        type: "array"
        description: "List of scheduled outages. Property is mandatory but may contain\
          \ and empty list if no outages are scheduled"
        items:
          $ref: "#/definitions/DiscoveryOutage"
  DiscoveryOutage:
    type: "object"
    required:
      - "duration"
      - "explanation"
      - "outageTime"
    properties:
      outageTime:
        type: "string"
        description: "Date and time that the outage is scheduled to begin"
        x-cds-type: "DateTimeString"
      duration:
        type: "number"
        description: "Planned duration of the outage in minutes"
      isPartial:
        type: "boolean"
        description: "Flag that indicates, if present and set to true, that the outage\
          \ is only partial meaning that only a subset of normally available end points\
          \ will be affected by the outage"
      explanation:
        type: "string"
        description: "Provides an explanation of the current outage that can be displayed\
          \ to an end customer"

  ResponseDiscoveryStatus:
    type: "object"
    required:
      - "links"
      - "data"
    properties:
      data:
        $ref: "#/definitions/ResponseDiscoveryStatus_data"
      links:
        $ref: "#/definitions/Links"
      meta:
        $ref: "#/definitions/Meta"
  ResponseDiscoveryStatus_data:
    required:
      - "status"
      - "updateTime"
    properties:
      status:
        type: "string"
        description: "Enumeration with values. OK (implementation is fully functional).\
          \ PARTIAL_FAILURE (one or more end points are unexpectedly unavailable).\
          \ UNAVAILABLE (the full implementation is unexpectedly unavailable). SCHEDULED_OUTAGE\
          \ (an advertised outage is in effect)"
        enum:
          - "OK"
          - "PARTIAL_FAILURE"
          - "UNAVAILABLE"
          - "SCHEDULED_OUTAGE"
      explanation:
        type: "string"
        description: "Provides an explanation of the current outage that can be displayed\
          \ to an end customer. Mandatory if the status property is any value other\
          \ than OK"
      detectionTime:
        type: "string"
        description: "The date and time that the current outage was detected. Should\
          \ only be present if the status property is PARTIAL_FAILURE or UNAVAILABLE"
        x-cds-type: "DateTimeString"
      expectedResolutionTime:
        type: "string"
        description: "The date and time that full service is expected to resume (if\
          \ known). Should not be present if the status property has a value of OK."
        x-cds-type: "DateTimeString"
      updateTime:
        type: "string"
        description: "The date and time that this status was last updated by the Data\
          \ Holder."
        x-cds-type: "DateTimeString"
  Links:
    type: "object"
    required:
      - "self"
    properties:
      self:
        type: "string"
        description: "Fully qualified link to this API call"
        x-cds-type: "URIString"
  Meta:
    type: "object"

parameters:
  RequestHeader_x-v:
    name: x-v
    in: header
    description: Version of the API end point requested by the client. Must be set to a positive integer. If the version(s) requested is not supported then the holder should respond with a 406 Not Acceptable. See [here](##request-headers)
    required: true
    type: string
  RequestHeader_x-min-v:
    name: x-min-v
    in: header
    description: Minimum version of the API end point requested by the client. Must be set to a positive integer if provided. The holder should respond with the highest supported version between [x-min-v](##request-headers) and [x-v](##request-headers). If all versions requested are not supported then the holder should respond with a 406 Not Acceptable.
    required: false
    type: string
